project:
  type: website

website:
  title: "temporary_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pete-jacobsson
      - icon: linkedin
        href: https://www.linkedin.com/in/pt-jacobsson/
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

